version: '3.7'
services:
  tinyproxy:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./tinyproxy.conf:/usr/etc/tinyproxy/tinyproxy.conf
      - ./tinyproxy.log:/var/log/tinyproxy/tinyproxy.log
    restart: always
